CBP-15766: Update label-artifact-version action to make labels REQUIRED param and ADD as default operation (#6)
* CBP-15766: labels made REQUIRED param and ADD as default operation

* CBP-15766: test workflows updated

* CBP-15766: organization-id added

* CBP-15766: revert organization-id addition

* CBP-15766: remove fixed

* CBP-15766: remove fixed

* CBP-15766: remove fixed

* CBP-15766: remove fixed

* CBP-15766: refactor

* CBP-15766: character restriction removed

* CBP-15766: echo

* CBP-15766: echo to printf

* CBP-15766: echo to printf

* CBP-15766: print response

* CBP-15766: add payload construction

* CBP-15766: remove payload construction

* CBP-15766: comments and refactor

* CBP-15766: escaped characters handling

* CBP-15766: escaped characters handling

* CBP-15766: escaped characters handling

* CBP-15766: escaped characters handling

* CBP-15766: redirection

* CBP-15766: logs

* CBP-15766: logs

* CBP-15766: add

* CBP-15766: revert

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,17 +4,15 @@ name: 'Label artifact version'
 description: 'Add or remove label(s) to an existing artifact version.'
 
 inputs:
-  component-id:
-    description: 'The ID of the component that the artifact belongs to.'
-    required: true
   artifact-id:
     description: 'The unique identifier of the artifact.'
     required: true
   labels:
     description: 'A comma-separated list of artifact labels. If the list is empty, and the operation is "REPLACE", all the existing labels will be removed.'
-    required: false
+    required: true
   operation:
-    description: 'The type of action to be performed with labels of an artifact. "ADD", "REMOVE" or "REPLACE" are options available. "REPLACE" is used as default value.'
+    description: 'The type of action to be performed with labels of an artifact. "ADD" and "REMOVE" are options available. "ADD" is used as default value.'
+    default: ADD
 
 runs:
   using: composite
@@ -23,38 +21,76 @@ runs:
       name: Label Artifact Version
       uses: docker://esolang/jq:latest
       run: |
-        #Create payload
-        echo '{ "component_id": "'"$INPUT_COMPONENT_ID"'", "artifact_id": "'"$INPUT_ARTIFACT_ID"'", ' > /tmp/payload.json 
+        # Set default operation to ADD if not provided
+        OPERATION=${INPUT_OPERATION:-ADD}
+        
+        # Perform API call based on operation
+        if [ "$OPERATION" = "ADD" ]; then
+          
+          # Create payload
+          
+          # Format labels as a JSON array    
+          formatted_labels=$(
+             echo "$INPUT_LABELS" | awk -F',' '{
+                 for (i=1;i<=NF;i++) {
+                    gsub(/"/, "\\\"",$i)          # escape double quotes
+                    printf "\"%s\"",$i
+                    if (i<NF) printf ","
+                 }
+             }'
+          )
+          
+          # Compose JSON payload
+          echo "{ \"artifact_id\": \"${INPUT_ARTIFACT_ID}\", \"labels\": [${formatted_labels}] }" > /tmp/payload.json
 
-         # convert to JSON format
-         formatted_labels=$(echo "$INPUT_LABELS" | sed -e 's/[][]//g' | awk -v RS=, -v ORS=, '{ gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "");  gsub(/\\"/, "\\\\\""); gsub(/"/, "\\\""); printf "\"%s\",", $0 }' | sed 's/,$//' | sed 's/^/[/; s/$/]/')
-         echo ' "labels": '"$formatted_labels">> /tmp/payload.json
+          # POST request to add labels
+          response=$(curl --fail-with-body -X 'POST' "$URL/v3/artifactinfos/$INPUT_ARTIFACT_ID/labels" \
+            -H "Authorization: Bearer $JWT" -H "Content-Type: application/json" \
+            --data-binary '@/tmp/payload.json') || command_failed=1
         
-        # operation argument is optional
-        if [ -n "$INPUT_OPERATION" ]; then
-          echo ', "operation": "'"$INPUT_OPERATION"'"' >> /tmp/payload.json
-        else
-          echo ', "operation": "'"REPLACE"'"' >> /tmp/payload.json
-        fi
+          # Check curl exit code
+          if [ ${command_failed:-0} -eq 1 ]; then
+            echo "Platform API call failed with error: '$response'"
+            exit 1
+          fi
         
-        echo ' }' >> /tmp/payload.json
+        else # If operation is REMOVE
+           # Function to URL-encode
+           urlencode() {
+              python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]), end='')" "$1"
+           }
         
-        # Make Platform API call to create label records for artifact info
-        response=$(curl --fail-with-body  -X 'PUT' "$URL/v3/components/$INPUT_COMPONENT_ID/artifactinfos/$INPUT_ARTIFACT_ID/labels" \
-          -H "Authorization: Bearer $JWT" -H "Content-Type: application/json" \
-          --data-binary '@/tmp/payload.json') || command_failed=1
-       
-        # Check curl exit code
-        if [ ${command_failed:-0} -eq 1 ];
-        then
-          echo "Platform API call failed with error: '$response'"
-          exit 1
+          # Build query string from labels
+          label_query=""
+          OLD_IFS="$IFS"
+          IFS=','
+          
+          for label in $INPUT_LABELS; do
+            encoded=$(urlencode "$label")
+            if [ -n "$label_query" ]; then
+              label_query="${label_query}&"
+            fi
+            label_query="${label_query}labels=${encoded}"
+          done
+          
+          IFS="$OLD_IFS"
+          
+          # DELETE request to remove labels
+          response=$(curl --fail-with-body -X 'DELETE' "$URL/v3/artifactinfos/$INPUT_ARTIFACT_ID/labels?$label_query" \
+           -H "Authorization: Bearer $JWT" -H "Content-Type: application/json") 
+           if [ $? -ne 0 ]; then
+             command_failed=1
+           fi
+
+         # Check curl exit code
+         if [ ${command_failed:-0} -eq 1 ]; then
+           echo "Platform API call failed with error: '$response'"
+           exit 1
+         fi
         fi
       env:
         JWT: ${{ cloudbees.api.token }}
         URL: ${{ cloudbees.api.url }}
         INPUT_ARTIFACT_ID: ${{ inputs.artifact-id }}
-        INPUT_COMPONENT_ID: ${{ inputs.component-id }}
         INPUT_LABELS: ${{ inputs.labels }}
         INPUT_OPERATION: ${{ inputs.operation }}
-
